name: Build Karbon and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            extension: .exe
            pyinstaller-args: --onefile --noconsole --name Karbon --icon=icon.ico
          - os: ubuntu-latest
            extension: ""
            pyinstaller-args: --onefile --noconsole --name Karbon
          - os: macos-latest
            extension: .app
            pyinstaller-args: --onefile --noconsole --name Karbon

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pyinstaller
        # ⬇️ Add PyInstaller path to environment manually
      - name: Add PyInstaller path to PATH
        if: runner.os != 'Windows'
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Debug PyInstaller availability
        run: |
          which pyinstaller || echo "pyinstaller not found"
          python -m pyinstaller --version || echo "pyinstaller module not found"

      - name: Build executable with PyInstaller
        run: python -m pyinstaller ui.py ${{ matrix.pyinstaller-args }}

      - name: Rename binary for upload
        shell: bash
        run: |
          mkdir -p upload
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cp -r "dist/Karbon.app" "upload/Karbon-${{ runner.os }}.app"
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp "dist/Karbon.exe" "upload/Karbon-${{ runner.os }}.exe"
          else
            cp "dist/Karbon" "upload/Karbon-${{ runner.os }}"
          fi

      - name: Get short commit hash
        id: vars
        shell: bash
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ env.SHORT_SHA }}"
          name: "Karbon Build ${{ env.SHORT_SHA }}"
          draft: false
          prerelease: false
          files: upload/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
